CREATE TABLE IF NOT EXISTS library_resources (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    school_id INT UNSIGNED NOT NULL,
    created_by INT UNSIGNED NOT NULL,
    source_material_id INT UNSIGNED DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    resource_kind ENUM('lesson', 'book', 'module', 'worksheet', 'reference', 'other') NOT NULL DEFAULT 'other',
    subject_id INT UNSIGNED DEFAULT NULL,
    type VARCHAR(16) NOT NULL DEFAULT 'file',
    content LONGTEXT DEFAULT NULL,
    body TEXT DEFAULT NULL,
    file_path VARCHAR(500) DEFAULT NULL,
    original_name VARCHAR(255) DEFAULT NULL,
    mime_type VARCHAR(120) DEFAULT NULL,
    file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    file_access_mode ENUM('view_only', 'downloadable') NOT NULL DEFAULT 'downloadable',
    external_link VARCHAR(500) DEFAULT NULL,
    status ENUM('pending', 'published', 'rejected') NOT NULL DEFAULT 'pending',
    audience ENUM('all', 'teachers') NOT NULL DEFAULT 'all',
    rejection_note TEXT DEFAULT NULL,
    approved_by INT UNSIGNED DEFAULT NULL,
    approved_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_library_school (school_id),
    KEY idx_library_status (school_id, status),
    KEY idx_library_subject (subject_id),
    KEY idx_library_source_material (source_material_id),
    KEY idx_library_file_path (file_path(191)),
    CONSTRAINT fk_library_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
    CONSTRAINT fk_library_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_library_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
    CONSTRAINT fk_library_source_material FOREIGN KEY (source_material_id) REFERENCES materials(id) ON DELETE SET NULL,
    CONSTRAINT fk_library_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE materials
    ADD COLUMN library_resource_id INT UNSIGNED NULL DEFAULT NULL AFTER teacher_id,
    ADD KEY idx_materials_library (library_resource_id),
    ADD CONSTRAINT fk_materials_library FOREIGN KEY (library_resource_id) REFERENCES library_resources(id) ON DELETE SET NULL;
